services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/01-database.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s


  redis:
    image: redis:7

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    env_file:
      - ./.env

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    restart: unless-stopped


volumes:
  postgres_data:
  redis_data: